/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class A3 */

#ifndef _Included_A3
#define _Included_A3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     A3
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_A3_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     A3
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_A3_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     A3
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_A3_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     A3
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_A3_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
